### ISSUE TITLE
r-testthat 3.1.4 r41 not built for linux-ppc64le

### ISSUE THREAD

**Issue by rolweber** [conda-forge/r-testthat-feedstock#28]
### Comment:

r-testthat 3.1.3 was built for linux-ppc64le, but 3.1.4 no more.
Was that an intentional decision to drop the support, or just some kind of mishap?
The PR doesn't look as if it drops a platform: https://github.com/conda-forge/r-testthat-feedstock/pull/27/files

```txt
conda-search-forge "r-testthat>=3.1=r41*" --platform linux-ppc64le
Loading channels: done
# Name                       Version           Build  Channel             
r-testthat                     3.1.0   r41h6203a36_0  conda-forge         
r-testthat                     3.1.1   r41h6203a36_0  conda-forge         
r-testthat                     3.1.2   r41h6203a36_0  conda-forge         
r-testthat                     3.1.3   r41ha35a809_0  conda-forge         
```

**Comment by mfansler** [comment]
It doesn't look intentional - sometimes CI has sporadic failures in the post-merge builds and these go unnoticed. Unfortunately, those build logs are expired, so 🤷 . There are newer versions - hopefully these suffice.

If you really do need that specific version built, an out-of-sequence build could be run. However, this is not so trivial (needs a new branch made), so it would be preferable to not. Please let us know if you still need it! Otherwise, I'd suggest we close this and add a "won't fix" label.

**Comment by rolweber** [comment]
Thanks for the explanation. I'm closing this issue, but don't have permission to add the label.
